// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex/enums.proto

package seiprotocol.seichain.dex;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code seiprotocol.seichain.dex.PositionDirection}
   */
  public enum PositionDirection
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LONG = 0;</code>
     */
    LONG(0),
    /**
     * <code>SHORT = 1;</code>
     */
    SHORT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LONG = 0;</code>
     */
    public static final int LONG_VALUE = 0;
    /**
     * <code>SHORT = 1;</code>
     */
    public static final int SHORT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PositionDirection valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PositionDirection forNumber(int value) {
      switch (value) {
        case 0: return LONG;
        case 1: return SHORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PositionDirection>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PositionDirection> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PositionDirection>() {
            public PositionDirection findValueByNumber(int number) {
              return PositionDirection.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.Enums.getDescriptor().getEnumTypes().get(0);
    }

    private static final PositionDirection[] VALUES = values();

    public static PositionDirection valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PositionDirection(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:seiprotocol.seichain.dex.PositionDirection)
  }

  /**
   * Protobuf enum {@code seiprotocol.seichain.dex.PositionEffect}
   */
  public enum PositionEffect
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OPEN = 0;</code>
     */
    OPEN(0),
    /**
     * <code>CLOSE = 1;</code>
     */
    CLOSE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OPEN = 0;</code>
     */
    public static final int OPEN_VALUE = 0;
    /**
     * <code>CLOSE = 1;</code>
     */
    public static final int CLOSE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PositionEffect valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PositionEffect forNumber(int value) {
      switch (value) {
        case 0: return OPEN;
        case 1: return CLOSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PositionEffect>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PositionEffect> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PositionEffect>() {
            public PositionEffect findValueByNumber(int number) {
              return PositionEffect.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.Enums.getDescriptor().getEnumTypes().get(1);
    }

    private static final PositionEffect[] VALUES = values();

    public static PositionEffect valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PositionEffect(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:seiprotocol.seichain.dex.PositionEffect)
  }

  /**
   * Protobuf enum {@code seiprotocol.seichain.dex.OrderType}
   */
  public enum OrderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LIMIT = 0;</code>
     */
    LIMIT(0),
    /**
     * <code>MARKET = 1;</code>
     */
    MARKET(1),
    /**
     * <pre>
     * fill-or-kill market order
     * </pre>
     *
     * <code>FOKMARKET = 3;</code>
     */
    FOKMARKET(3),
    /**
     * <pre>
     * fill-or-kill market by value order
     * </pre>
     *
     * <code>FOKMARKETBYVALUE = 4;</code>
     */
    FOKMARKETBYVALUE(4),
    /**
     * <code>STOPLOSS = 5;</code>
     */
    STOPLOSS(5),
    /**
     * <code>STOPLIMIT = 6;</code>
     */
    STOPLIMIT(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LIMIT = 0;</code>
     */
    public static final int LIMIT_VALUE = 0;
    /**
     * <code>MARKET = 1;</code>
     */
    public static final int MARKET_VALUE = 1;
    /**
     * <pre>
     * fill-or-kill market order
     * </pre>
     *
     * <code>FOKMARKET = 3;</code>
     */
    public static final int FOKMARKET_VALUE = 3;
    /**
     * <pre>
     * fill-or-kill market by value order
     * </pre>
     *
     * <code>FOKMARKETBYVALUE = 4;</code>
     */
    public static final int FOKMARKETBYVALUE_VALUE = 4;
    /**
     * <code>STOPLOSS = 5;</code>
     */
    public static final int STOPLOSS_VALUE = 5;
    /**
     * <code>STOPLIMIT = 6;</code>
     */
    public static final int STOPLIMIT_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OrderType forNumber(int value) {
      switch (value) {
        case 0: return LIMIT;
        case 1: return MARKET;
        case 3: return FOKMARKET;
        case 4: return FOKMARKETBYVALUE;
        case 5: return STOPLOSS;
        case 6: return STOPLIMIT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderType>() {
            public OrderType findValueByNumber(int number) {
              return OrderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.Enums.getDescriptor().getEnumTypes().get(2);
    }

    private static final OrderType[] VALUES = values();

    public static OrderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:seiprotocol.seichain.dex.OrderType)
  }

  /**
   * Protobuf enum {@code seiprotocol.seichain.dex.Unit}
   */
  public enum Unit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STANDARD = 0;</code>
     */
    STANDARD(0),
    /**
     * <code>MILLI = 1;</code>
     */
    MILLI(1),
    /**
     * <code>MICRO = 2;</code>
     */
    MICRO(2),
    /**
     * <code>NANO = 3;</code>
     */
    NANO(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STANDARD = 0;</code>
     */
    public static final int STANDARD_VALUE = 0;
    /**
     * <code>MILLI = 1;</code>
     */
    public static final int MILLI_VALUE = 1;
    /**
     * <code>MICRO = 2;</code>
     */
    public static final int MICRO_VALUE = 2;
    /**
     * <code>NANO = 3;</code>
     */
    public static final int NANO_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Unit valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Unit forNumber(int value) {
      switch (value) {
        case 0: return STANDARD;
        case 1: return MILLI;
        case 2: return MICRO;
        case 3: return NANO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Unit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Unit> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Unit>() {
            public Unit findValueByNumber(int number) {
              return Unit.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.Enums.getDescriptor().getEnumTypes().get(3);
    }

    private static final Unit[] VALUES = values();

    public static Unit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Unit(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:seiprotocol.seichain.dex.Unit)
  }

  /**
   * Protobuf enum {@code seiprotocol.seichain.dex.OrderStatus}
   */
  public enum OrderStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLACED = 0;</code>
     */
    PLACED(0),
    /**
     * <code>FAILED_TO_PLACE = 1;</code>
     */
    FAILED_TO_PLACE(1),
    /**
     * <code>CANCELLED = 2;</code>
     */
    CANCELLED(2),
    /**
     * <code>FULFILLED = 3;</code>
     */
    FULFILLED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PLACED = 0;</code>
     */
    public static final int PLACED_VALUE = 0;
    /**
     * <code>FAILED_TO_PLACE = 1;</code>
     */
    public static final int FAILED_TO_PLACE_VALUE = 1;
    /**
     * <code>CANCELLED = 2;</code>
     */
    public static final int CANCELLED_VALUE = 2;
    /**
     * <code>FULFILLED = 3;</code>
     */
    public static final int FULFILLED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OrderStatus forNumber(int value) {
      switch (value) {
        case 0: return PLACED;
        case 1: return FAILED_TO_PLACE;
        case 2: return CANCELLED;
        case 3: return FULFILLED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderStatus>() {
            public OrderStatus findValueByNumber(int number) {
              return OrderStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.Enums.getDescriptor().getEnumTypes().get(4);
    }

    private static final OrderStatus[] VALUES = values();

    public static OrderStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:seiprotocol.seichain.dex.OrderStatus)
  }

  /**
   * Protobuf enum {@code seiprotocol.seichain.dex.CancellationInitiator}
   */
  public enum CancellationInitiator
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER = 0;</code>
     */
    USER(0),
    /**
     * <code>LIQUIDATED = 1;</code>
     */
    LIQUIDATED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>USER = 0;</code>
     */
    public static final int USER_VALUE = 0;
    /**
     * <code>LIQUIDATED = 1;</code>
     */
    public static final int LIQUIDATED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CancellationInitiator valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CancellationInitiator forNumber(int value) {
      switch (value) {
        case 0: return USER;
        case 1: return LIQUIDATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CancellationInitiator>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CancellationInitiator> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CancellationInitiator>() {
            public CancellationInitiator findValueByNumber(int number) {
              return CancellationInitiator.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.Enums.getDescriptor().getEnumTypes().get(5);
    }

    private static final CancellationInitiator[] VALUES = values();

    public static CancellationInitiator valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CancellationInitiator(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:seiprotocol.seichain.dex.CancellationInitiator)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017dex/enums.proto\022\030seiprotocol.seichain." +
      "dex*(\n\021PositionDirection\022\010\n\004LONG\020\000\022\t\n\005SH" +
      "ORT\020\001*%\n\016PositionEffect\022\010\n\004OPEN\020\000\022\t\n\005CLO" +
      "SE\020\001*d\n\tOrderType\022\t\n\005LIMIT\020\000\022\n\n\006MARKET\020\001" +
      "\022\r\n\tFOKMARKET\020\003\022\024\n\020FOKMARKETBYVALUE\020\004\022\014\n" +
      "\010STOPLOSS\020\005\022\r\n\tSTOPLIMIT\020\006*4\n\004Unit\022\014\n\010ST" +
      "ANDARD\020\000\022\t\n\005MILLI\020\001\022\t\n\005MICRO\020\002\022\010\n\004NANO\020\003" +
      "*L\n\013OrderStatus\022\n\n\006PLACED\020\000\022\023\n\017FAILED_TO" +
      "_PLACE\020\001\022\r\n\tCANCELLED\020\002\022\r\n\tFULFILLED\020\003*1" +
      "\n\025CancellationInitiator\022\010\n\004USER\020\000\022\016\n\nLIQ" +
      "UIDATED\020\001B/Z-github.com/sei-protocol/sei" +
      "-chain/x/dex/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
