// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex/params.proto

package seiprotocol.seichain.dex;

public final class ParamsOuterClass {
  private ParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seiprotocol.seichain.dex.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 price_snapshot_retention = 1 [(.gogoproto.jsontag) = "price_snapshot_retention", (.gogoproto.moretags) = "yaml:&#92;"price_snapshot_retention&#92;""];</code>
     * @return The priceSnapshotRetention.
     */
    long getPriceSnapshotRetention();

    /**
     * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
     * @return The sudoCallGasPrice.
     */
    java.lang.String getSudoCallGasPrice();
    /**
     * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
     * @return The bytes for sudoCallGasPrice.
     */
    com.google.protobuf.ByteString
        getSudoCallGasPriceBytes();

    /**
     * <code>uint64 begin_block_gas_limit = 3 [(.gogoproto.jsontag) = "begin_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"begin_block_gas_limit&#92;""];</code>
     * @return The beginBlockGasLimit.
     */
    long getBeginBlockGasLimit();

    /**
     * <code>uint64 end_block_gas_limit = 4 [(.gogoproto.jsontag) = "end_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"end_block_gas_limit&#92;""];</code>
     * @return The endBlockGasLimit.
     */
    long getEndBlockGasLimit();

    /**
     * <code>uint64 default_gas_per_order = 5 [(.gogoproto.jsontag) = "default_gas_per_order", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_order&#92;""];</code>
     * @return The defaultGasPerOrder.
     */
    long getDefaultGasPerOrder();

    /**
     * <code>uint64 default_gas_per_cancel = 6 [(.gogoproto.jsontag) = "default_gas_per_cancel", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_cancel&#92;""];</code>
     * @return The defaultGasPerCancel.
     */
    long getDefaultGasPerCancel();

    /**
     * <code>uint64 min_rent_deposit = 7 [(.gogoproto.jsontag) = "min_rent_deposit", (.gogoproto.moretags) = "yaml:&#92;"min_rent_deposit&#92;""];</code>
     * @return The minRentDeposit.
     */
    long getMinRentDeposit();

    /**
     * <code>uint64 gas_allowance_per_settlement = 8 [(.gogoproto.jsontag) = "gas_allowance_per_settlement", (.gogoproto.moretags) = "yaml:&#92;"gas_allowance_per_settlement&#92;""];</code>
     * @return The gasAllowancePerSettlement.
     */
    long getGasAllowancePerSettlement();

    /**
     * <code>uint64 min_processable_rent = 9 [(.gogoproto.jsontag) = "min_processable_rent", (.gogoproto.moretags) = "yaml:&#92;"min_processable_rent&#92;""];</code>
     * @return The minProcessableRent.
     */
    long getMinProcessableRent();

    /**
     * <code>uint64 order_book_entries_per_load = 10 [(.gogoproto.jsontag) = "order_book_entries_per_load", (.gogoproto.moretags) = "yaml:&#92;"order_book_entries_per_load&#92;""];</code>
     * @return The orderBookEntriesPerLoad.
     */
    long getOrderBookEntriesPerLoad();

    /**
     * <code>uint64 contract_unsuspend_cost = 11 [(.gogoproto.jsontag) = "contract_unsuspend_cost", (.gogoproto.moretags) = "yaml:&#92;"contract_unsuspend_cost&#92;""];</code>
     * @return The contractUnsuspendCost.
     */
    long getContractUnsuspendCost();

    /**
     * <code>uint64 max_order_per_price = 12 [(.gogoproto.jsontag) = "max_order_per_price", (.gogoproto.moretags) = "yaml:&#92;"max_order_per_price&#92;""];</code>
     * @return The maxOrderPerPrice.
     */
    long getMaxOrderPerPrice();

    /**
     * <code>uint64 max_pairs_per_contract = 13 [(.gogoproto.jsontag) = "max_pairs_per_contract", (.gogoproto.moretags) = "yaml:&#92;"max_pairs_per_contract&#92;""];</code>
     * @return The maxPairsPerContract.
     */
    long getMaxPairsPerContract();
  }
  /**
   * <pre>
   * Params defines the parameters for the module.
   * </pre>
   *
   * Protobuf type {@code seiprotocol.seichain.dex.Params}
   */
  public static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seiprotocol.seichain.dex.Params)
      ParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
      sudoCallGasPrice_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Params();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return seiprotocol.seichain.dex.ParamsOuterClass.internal_static_seiprotocol_seichain_dex_Params_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return seiprotocol.seichain.dex.ParamsOuterClass.internal_static_seiprotocol_seichain_dex_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              seiprotocol.seichain.dex.ParamsOuterClass.Params.class, seiprotocol.seichain.dex.ParamsOuterClass.Params.Builder.class);
    }

    public static final int PRICE_SNAPSHOT_RETENTION_FIELD_NUMBER = 1;
    private long priceSnapshotRetention_ = 0L;
    /**
     * <code>uint64 price_snapshot_retention = 1 [(.gogoproto.jsontag) = "price_snapshot_retention", (.gogoproto.moretags) = "yaml:&#92;"price_snapshot_retention&#92;""];</code>
     * @return The priceSnapshotRetention.
     */
    @java.lang.Override
    public long getPriceSnapshotRetention() {
      return priceSnapshotRetention_;
    }

    public static final int SUDO_CALL_GAS_PRICE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sudoCallGasPrice_ = "";
    /**
     * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
     * @return The sudoCallGasPrice.
     */
    @java.lang.Override
    public java.lang.String getSudoCallGasPrice() {
      java.lang.Object ref = sudoCallGasPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sudoCallGasPrice_ = s;
        return s;
      }
    }
    /**
     * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
     * @return The bytes for sudoCallGasPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSudoCallGasPriceBytes() {
      java.lang.Object ref = sudoCallGasPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sudoCallGasPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEGIN_BLOCK_GAS_LIMIT_FIELD_NUMBER = 3;
    private long beginBlockGasLimit_ = 0L;
    /**
     * <code>uint64 begin_block_gas_limit = 3 [(.gogoproto.jsontag) = "begin_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"begin_block_gas_limit&#92;""];</code>
     * @return The beginBlockGasLimit.
     */
    @java.lang.Override
    public long getBeginBlockGasLimit() {
      return beginBlockGasLimit_;
    }

    public static final int END_BLOCK_GAS_LIMIT_FIELD_NUMBER = 4;
    private long endBlockGasLimit_ = 0L;
    /**
     * <code>uint64 end_block_gas_limit = 4 [(.gogoproto.jsontag) = "end_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"end_block_gas_limit&#92;""];</code>
     * @return The endBlockGasLimit.
     */
    @java.lang.Override
    public long getEndBlockGasLimit() {
      return endBlockGasLimit_;
    }

    public static final int DEFAULT_GAS_PER_ORDER_FIELD_NUMBER = 5;
    private long defaultGasPerOrder_ = 0L;
    /**
     * <code>uint64 default_gas_per_order = 5 [(.gogoproto.jsontag) = "default_gas_per_order", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_order&#92;""];</code>
     * @return The defaultGasPerOrder.
     */
    @java.lang.Override
    public long getDefaultGasPerOrder() {
      return defaultGasPerOrder_;
    }

    public static final int DEFAULT_GAS_PER_CANCEL_FIELD_NUMBER = 6;
    private long defaultGasPerCancel_ = 0L;
    /**
     * <code>uint64 default_gas_per_cancel = 6 [(.gogoproto.jsontag) = "default_gas_per_cancel", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_cancel&#92;""];</code>
     * @return The defaultGasPerCancel.
     */
    @java.lang.Override
    public long getDefaultGasPerCancel() {
      return defaultGasPerCancel_;
    }

    public static final int MIN_RENT_DEPOSIT_FIELD_NUMBER = 7;
    private long minRentDeposit_ = 0L;
    /**
     * <code>uint64 min_rent_deposit = 7 [(.gogoproto.jsontag) = "min_rent_deposit", (.gogoproto.moretags) = "yaml:&#92;"min_rent_deposit&#92;""];</code>
     * @return The minRentDeposit.
     */
    @java.lang.Override
    public long getMinRentDeposit() {
      return minRentDeposit_;
    }

    public static final int GAS_ALLOWANCE_PER_SETTLEMENT_FIELD_NUMBER = 8;
    private long gasAllowancePerSettlement_ = 0L;
    /**
     * <code>uint64 gas_allowance_per_settlement = 8 [(.gogoproto.jsontag) = "gas_allowance_per_settlement", (.gogoproto.moretags) = "yaml:&#92;"gas_allowance_per_settlement&#92;""];</code>
     * @return The gasAllowancePerSettlement.
     */
    @java.lang.Override
    public long getGasAllowancePerSettlement() {
      return gasAllowancePerSettlement_;
    }

    public static final int MIN_PROCESSABLE_RENT_FIELD_NUMBER = 9;
    private long minProcessableRent_ = 0L;
    /**
     * <code>uint64 min_processable_rent = 9 [(.gogoproto.jsontag) = "min_processable_rent", (.gogoproto.moretags) = "yaml:&#92;"min_processable_rent&#92;""];</code>
     * @return The minProcessableRent.
     */
    @java.lang.Override
    public long getMinProcessableRent() {
      return minProcessableRent_;
    }

    public static final int ORDER_BOOK_ENTRIES_PER_LOAD_FIELD_NUMBER = 10;
    private long orderBookEntriesPerLoad_ = 0L;
    /**
     * <code>uint64 order_book_entries_per_load = 10 [(.gogoproto.jsontag) = "order_book_entries_per_load", (.gogoproto.moretags) = "yaml:&#92;"order_book_entries_per_load&#92;""];</code>
     * @return The orderBookEntriesPerLoad.
     */
    @java.lang.Override
    public long getOrderBookEntriesPerLoad() {
      return orderBookEntriesPerLoad_;
    }

    public static final int CONTRACT_UNSUSPEND_COST_FIELD_NUMBER = 11;
    private long contractUnsuspendCost_ = 0L;
    /**
     * <code>uint64 contract_unsuspend_cost = 11 [(.gogoproto.jsontag) = "contract_unsuspend_cost", (.gogoproto.moretags) = "yaml:&#92;"contract_unsuspend_cost&#92;""];</code>
     * @return The contractUnsuspendCost.
     */
    @java.lang.Override
    public long getContractUnsuspendCost() {
      return contractUnsuspendCost_;
    }

    public static final int MAX_ORDER_PER_PRICE_FIELD_NUMBER = 12;
    private long maxOrderPerPrice_ = 0L;
    /**
     * <code>uint64 max_order_per_price = 12 [(.gogoproto.jsontag) = "max_order_per_price", (.gogoproto.moretags) = "yaml:&#92;"max_order_per_price&#92;""];</code>
     * @return The maxOrderPerPrice.
     */
    @java.lang.Override
    public long getMaxOrderPerPrice() {
      return maxOrderPerPrice_;
    }

    public static final int MAX_PAIRS_PER_CONTRACT_FIELD_NUMBER = 13;
    private long maxPairsPerContract_ = 0L;
    /**
     * <code>uint64 max_pairs_per_contract = 13 [(.gogoproto.jsontag) = "max_pairs_per_contract", (.gogoproto.moretags) = "yaml:&#92;"max_pairs_per_contract&#92;""];</code>
     * @return The maxPairsPerContract.
     */
    @java.lang.Override
    public long getMaxPairsPerContract() {
      return maxPairsPerContract_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (priceSnapshotRetention_ != 0L) {
        output.writeUInt64(1, priceSnapshotRetention_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sudoCallGasPrice_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sudoCallGasPrice_);
      }
      if (beginBlockGasLimit_ != 0L) {
        output.writeUInt64(3, beginBlockGasLimit_);
      }
      if (endBlockGasLimit_ != 0L) {
        output.writeUInt64(4, endBlockGasLimit_);
      }
      if (defaultGasPerOrder_ != 0L) {
        output.writeUInt64(5, defaultGasPerOrder_);
      }
      if (defaultGasPerCancel_ != 0L) {
        output.writeUInt64(6, defaultGasPerCancel_);
      }
      if (minRentDeposit_ != 0L) {
        output.writeUInt64(7, minRentDeposit_);
      }
      if (gasAllowancePerSettlement_ != 0L) {
        output.writeUInt64(8, gasAllowancePerSettlement_);
      }
      if (minProcessableRent_ != 0L) {
        output.writeUInt64(9, minProcessableRent_);
      }
      if (orderBookEntriesPerLoad_ != 0L) {
        output.writeUInt64(10, orderBookEntriesPerLoad_);
      }
      if (contractUnsuspendCost_ != 0L) {
        output.writeUInt64(11, contractUnsuspendCost_);
      }
      if (maxOrderPerPrice_ != 0L) {
        output.writeUInt64(12, maxOrderPerPrice_);
      }
      if (maxPairsPerContract_ != 0L) {
        output.writeUInt64(13, maxPairsPerContract_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (priceSnapshotRetention_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, priceSnapshotRetention_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sudoCallGasPrice_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sudoCallGasPrice_);
      }
      if (beginBlockGasLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, beginBlockGasLimit_);
      }
      if (endBlockGasLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, endBlockGasLimit_);
      }
      if (defaultGasPerOrder_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, defaultGasPerOrder_);
      }
      if (defaultGasPerCancel_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, defaultGasPerCancel_);
      }
      if (minRentDeposit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, minRentDeposit_);
      }
      if (gasAllowancePerSettlement_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, gasAllowancePerSettlement_);
      }
      if (minProcessableRent_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, minProcessableRent_);
      }
      if (orderBookEntriesPerLoad_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, orderBookEntriesPerLoad_);
      }
      if (contractUnsuspendCost_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, contractUnsuspendCost_);
      }
      if (maxOrderPerPrice_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, maxOrderPerPrice_);
      }
      if (maxPairsPerContract_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(13, maxPairsPerContract_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof seiprotocol.seichain.dex.ParamsOuterClass.Params)) {
        return super.equals(obj);
      }
      seiprotocol.seichain.dex.ParamsOuterClass.Params other = (seiprotocol.seichain.dex.ParamsOuterClass.Params) obj;

      if (getPriceSnapshotRetention()
          != other.getPriceSnapshotRetention()) return false;
      if (!getSudoCallGasPrice()
          .equals(other.getSudoCallGasPrice())) return false;
      if (getBeginBlockGasLimit()
          != other.getBeginBlockGasLimit()) return false;
      if (getEndBlockGasLimit()
          != other.getEndBlockGasLimit()) return false;
      if (getDefaultGasPerOrder()
          != other.getDefaultGasPerOrder()) return false;
      if (getDefaultGasPerCancel()
          != other.getDefaultGasPerCancel()) return false;
      if (getMinRentDeposit()
          != other.getMinRentDeposit()) return false;
      if (getGasAllowancePerSettlement()
          != other.getGasAllowancePerSettlement()) return false;
      if (getMinProcessableRent()
          != other.getMinProcessableRent()) return false;
      if (getOrderBookEntriesPerLoad()
          != other.getOrderBookEntriesPerLoad()) return false;
      if (getContractUnsuspendCost()
          != other.getContractUnsuspendCost()) return false;
      if (getMaxOrderPerPrice()
          != other.getMaxOrderPerPrice()) return false;
      if (getMaxPairsPerContract()
          != other.getMaxPairsPerContract()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRICE_SNAPSHOT_RETENTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPriceSnapshotRetention());
      hash = (37 * hash) + SUDO_CALL_GAS_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getSudoCallGasPrice().hashCode();
      hash = (37 * hash) + BEGIN_BLOCK_GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBeginBlockGasLimit());
      hash = (37 * hash) + END_BLOCK_GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndBlockGasLimit());
      hash = (37 * hash) + DEFAULT_GAS_PER_ORDER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDefaultGasPerOrder());
      hash = (37 * hash) + DEFAULT_GAS_PER_CANCEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDefaultGasPerCancel());
      hash = (37 * hash) + MIN_RENT_DEPOSIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMinRentDeposit());
      hash = (37 * hash) + GAS_ALLOWANCE_PER_SETTLEMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGasAllowancePerSettlement());
      hash = (37 * hash) + MIN_PROCESSABLE_RENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMinProcessableRent());
      hash = (37 * hash) + ORDER_BOOK_ENTRIES_PER_LOAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderBookEntriesPerLoad());
      hash = (37 * hash) + CONTRACT_UNSUSPEND_COST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getContractUnsuspendCost());
      hash = (37 * hash) + MAX_ORDER_PER_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxOrderPerPrice());
      hash = (37 * hash) + MAX_PAIRS_PER_CONTRACT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxPairsPerContract());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.dex.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(seiprotocol.seichain.dex.ParamsOuterClass.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Params defines the parameters for the module.
     * </pre>
     *
     * Protobuf type {@code seiprotocol.seichain.dex.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seiprotocol.seichain.dex.Params)
        seiprotocol.seichain.dex.ParamsOuterClass.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return seiprotocol.seichain.dex.ParamsOuterClass.internal_static_seiprotocol_seichain_dex_Params_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return seiprotocol.seichain.dex.ParamsOuterClass.internal_static_seiprotocol_seichain_dex_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                seiprotocol.seichain.dex.ParamsOuterClass.Params.class, seiprotocol.seichain.dex.ParamsOuterClass.Params.Builder.class);
      }

      // Construct using seiprotocol.seichain.dex.ParamsOuterClass.Params.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        priceSnapshotRetention_ = 0L;
        sudoCallGasPrice_ = "";
        beginBlockGasLimit_ = 0L;
        endBlockGasLimit_ = 0L;
        defaultGasPerOrder_ = 0L;
        defaultGasPerCancel_ = 0L;
        minRentDeposit_ = 0L;
        gasAllowancePerSettlement_ = 0L;
        minProcessableRent_ = 0L;
        orderBookEntriesPerLoad_ = 0L;
        contractUnsuspendCost_ = 0L;
        maxOrderPerPrice_ = 0L;
        maxPairsPerContract_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return seiprotocol.seichain.dex.ParamsOuterClass.internal_static_seiprotocol_seichain_dex_Params_descriptor;
      }

      @java.lang.Override
      public seiprotocol.seichain.dex.ParamsOuterClass.Params getDefaultInstanceForType() {
        return seiprotocol.seichain.dex.ParamsOuterClass.Params.getDefaultInstance();
      }

      @java.lang.Override
      public seiprotocol.seichain.dex.ParamsOuterClass.Params build() {
        seiprotocol.seichain.dex.ParamsOuterClass.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public seiprotocol.seichain.dex.ParamsOuterClass.Params buildPartial() {
        seiprotocol.seichain.dex.ParamsOuterClass.Params result = new seiprotocol.seichain.dex.ParamsOuterClass.Params(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(seiprotocol.seichain.dex.ParamsOuterClass.Params result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.priceSnapshotRetention_ = priceSnapshotRetention_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sudoCallGasPrice_ = sudoCallGasPrice_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.beginBlockGasLimit_ = beginBlockGasLimit_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.endBlockGasLimit_ = endBlockGasLimit_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.defaultGasPerOrder_ = defaultGasPerOrder_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.defaultGasPerCancel_ = defaultGasPerCancel_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.minRentDeposit_ = minRentDeposit_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.gasAllowancePerSettlement_ = gasAllowancePerSettlement_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.minProcessableRent_ = minProcessableRent_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.orderBookEntriesPerLoad_ = orderBookEntriesPerLoad_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.contractUnsuspendCost_ = contractUnsuspendCost_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.maxOrderPerPrice_ = maxOrderPerPrice_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.maxPairsPerContract_ = maxPairsPerContract_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof seiprotocol.seichain.dex.ParamsOuterClass.Params) {
          return mergeFrom((seiprotocol.seichain.dex.ParamsOuterClass.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(seiprotocol.seichain.dex.ParamsOuterClass.Params other) {
        if (other == seiprotocol.seichain.dex.ParamsOuterClass.Params.getDefaultInstance()) return this;
        if (other.getPriceSnapshotRetention() != 0L) {
          setPriceSnapshotRetention(other.getPriceSnapshotRetention());
        }
        if (!other.getSudoCallGasPrice().isEmpty()) {
          sudoCallGasPrice_ = other.sudoCallGasPrice_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getBeginBlockGasLimit() != 0L) {
          setBeginBlockGasLimit(other.getBeginBlockGasLimit());
        }
        if (other.getEndBlockGasLimit() != 0L) {
          setEndBlockGasLimit(other.getEndBlockGasLimit());
        }
        if (other.getDefaultGasPerOrder() != 0L) {
          setDefaultGasPerOrder(other.getDefaultGasPerOrder());
        }
        if (other.getDefaultGasPerCancel() != 0L) {
          setDefaultGasPerCancel(other.getDefaultGasPerCancel());
        }
        if (other.getMinRentDeposit() != 0L) {
          setMinRentDeposit(other.getMinRentDeposit());
        }
        if (other.getGasAllowancePerSettlement() != 0L) {
          setGasAllowancePerSettlement(other.getGasAllowancePerSettlement());
        }
        if (other.getMinProcessableRent() != 0L) {
          setMinProcessableRent(other.getMinProcessableRent());
        }
        if (other.getOrderBookEntriesPerLoad() != 0L) {
          setOrderBookEntriesPerLoad(other.getOrderBookEntriesPerLoad());
        }
        if (other.getContractUnsuspendCost() != 0L) {
          setContractUnsuspendCost(other.getContractUnsuspendCost());
        }
        if (other.getMaxOrderPerPrice() != 0L) {
          setMaxOrderPerPrice(other.getMaxOrderPerPrice());
        }
        if (other.getMaxPairsPerContract() != 0L) {
          setMaxPairsPerContract(other.getMaxPairsPerContract());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                priceSnapshotRetention_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                sudoCallGasPrice_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                beginBlockGasLimit_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                endBlockGasLimit_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                defaultGasPerOrder_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                defaultGasPerCancel_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                minRentDeposit_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                gasAllowancePerSettlement_ = input.readUInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                minProcessableRent_ = input.readUInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                orderBookEntriesPerLoad_ = input.readUInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                contractUnsuspendCost_ = input.readUInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 96: {
                maxOrderPerPrice_ = input.readUInt64();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              case 104: {
                maxPairsPerContract_ = input.readUInt64();
                bitField0_ |= 0x00001000;
                break;
              } // case 104
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long priceSnapshotRetention_ ;
      /**
       * <code>uint64 price_snapshot_retention = 1 [(.gogoproto.jsontag) = "price_snapshot_retention", (.gogoproto.moretags) = "yaml:&#92;"price_snapshot_retention&#92;""];</code>
       * @return The priceSnapshotRetention.
       */
      @java.lang.Override
      public long getPriceSnapshotRetention() {
        return priceSnapshotRetention_;
      }
      /**
       * <code>uint64 price_snapshot_retention = 1 [(.gogoproto.jsontag) = "price_snapshot_retention", (.gogoproto.moretags) = "yaml:&#92;"price_snapshot_retention&#92;""];</code>
       * @param value The priceSnapshotRetention to set.
       * @return This builder for chaining.
       */
      public Builder setPriceSnapshotRetention(long value) {

        priceSnapshotRetention_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 price_snapshot_retention = 1 [(.gogoproto.jsontag) = "price_snapshot_retention", (.gogoproto.moretags) = "yaml:&#92;"price_snapshot_retention&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceSnapshotRetention() {
        bitField0_ = (bitField0_ & ~0x00000001);
        priceSnapshotRetention_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sudoCallGasPrice_ = "";
      /**
       * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
       * @return The sudoCallGasPrice.
       */
      public java.lang.String getSudoCallGasPrice() {
        java.lang.Object ref = sudoCallGasPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sudoCallGasPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
       * @return The bytes for sudoCallGasPrice.
       */
      public com.google.protobuf.ByteString
          getSudoCallGasPriceBytes() {
        java.lang.Object ref = sudoCallGasPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sudoCallGasPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
       * @param value The sudoCallGasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setSudoCallGasPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sudoCallGasPrice_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSudoCallGasPrice() {
        sudoCallGasPrice_ = getDefaultInstance().getSudoCallGasPrice();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string sudo_call_gas_price = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "sudo_call_gas_price"];</code>
       * @param value The bytes for sudoCallGasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setSudoCallGasPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sudoCallGasPrice_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long beginBlockGasLimit_ ;
      /**
       * <code>uint64 begin_block_gas_limit = 3 [(.gogoproto.jsontag) = "begin_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"begin_block_gas_limit&#92;""];</code>
       * @return The beginBlockGasLimit.
       */
      @java.lang.Override
      public long getBeginBlockGasLimit() {
        return beginBlockGasLimit_;
      }
      /**
       * <code>uint64 begin_block_gas_limit = 3 [(.gogoproto.jsontag) = "begin_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"begin_block_gas_limit&#92;""];</code>
       * @param value The beginBlockGasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setBeginBlockGasLimit(long value) {

        beginBlockGasLimit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 begin_block_gas_limit = 3 [(.gogoproto.jsontag) = "begin_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"begin_block_gas_limit&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearBeginBlockGasLimit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        beginBlockGasLimit_ = 0L;
        onChanged();
        return this;
      }

      private long endBlockGasLimit_ ;
      /**
       * <code>uint64 end_block_gas_limit = 4 [(.gogoproto.jsontag) = "end_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"end_block_gas_limit&#92;""];</code>
       * @return The endBlockGasLimit.
       */
      @java.lang.Override
      public long getEndBlockGasLimit() {
        return endBlockGasLimit_;
      }
      /**
       * <code>uint64 end_block_gas_limit = 4 [(.gogoproto.jsontag) = "end_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"end_block_gas_limit&#92;""];</code>
       * @param value The endBlockGasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setEndBlockGasLimit(long value) {

        endBlockGasLimit_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 end_block_gas_limit = 4 [(.gogoproto.jsontag) = "end_block_gas_limit", (.gogoproto.moretags) = "yaml:&#92;"end_block_gas_limit&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearEndBlockGasLimit() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endBlockGasLimit_ = 0L;
        onChanged();
        return this;
      }

      private long defaultGasPerOrder_ ;
      /**
       * <code>uint64 default_gas_per_order = 5 [(.gogoproto.jsontag) = "default_gas_per_order", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_order&#92;""];</code>
       * @return The defaultGasPerOrder.
       */
      @java.lang.Override
      public long getDefaultGasPerOrder() {
        return defaultGasPerOrder_;
      }
      /**
       * <code>uint64 default_gas_per_order = 5 [(.gogoproto.jsontag) = "default_gas_per_order", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_order&#92;""];</code>
       * @param value The defaultGasPerOrder to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultGasPerOrder(long value) {

        defaultGasPerOrder_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 default_gas_per_order = 5 [(.gogoproto.jsontag) = "default_gas_per_order", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_order&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultGasPerOrder() {
        bitField0_ = (bitField0_ & ~0x00000010);
        defaultGasPerOrder_ = 0L;
        onChanged();
        return this;
      }

      private long defaultGasPerCancel_ ;
      /**
       * <code>uint64 default_gas_per_cancel = 6 [(.gogoproto.jsontag) = "default_gas_per_cancel", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_cancel&#92;""];</code>
       * @return The defaultGasPerCancel.
       */
      @java.lang.Override
      public long getDefaultGasPerCancel() {
        return defaultGasPerCancel_;
      }
      /**
       * <code>uint64 default_gas_per_cancel = 6 [(.gogoproto.jsontag) = "default_gas_per_cancel", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_cancel&#92;""];</code>
       * @param value The defaultGasPerCancel to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultGasPerCancel(long value) {

        defaultGasPerCancel_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 default_gas_per_cancel = 6 [(.gogoproto.jsontag) = "default_gas_per_cancel", (.gogoproto.moretags) = "yaml:&#92;"default_gas_per_cancel&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultGasPerCancel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        defaultGasPerCancel_ = 0L;
        onChanged();
        return this;
      }

      private long minRentDeposit_ ;
      /**
       * <code>uint64 min_rent_deposit = 7 [(.gogoproto.jsontag) = "min_rent_deposit", (.gogoproto.moretags) = "yaml:&#92;"min_rent_deposit&#92;""];</code>
       * @return The minRentDeposit.
       */
      @java.lang.Override
      public long getMinRentDeposit() {
        return minRentDeposit_;
      }
      /**
       * <code>uint64 min_rent_deposit = 7 [(.gogoproto.jsontag) = "min_rent_deposit", (.gogoproto.moretags) = "yaml:&#92;"min_rent_deposit&#92;""];</code>
       * @param value The minRentDeposit to set.
       * @return This builder for chaining.
       */
      public Builder setMinRentDeposit(long value) {

        minRentDeposit_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 min_rent_deposit = 7 [(.gogoproto.jsontag) = "min_rent_deposit", (.gogoproto.moretags) = "yaml:&#92;"min_rent_deposit&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinRentDeposit() {
        bitField0_ = (bitField0_ & ~0x00000040);
        minRentDeposit_ = 0L;
        onChanged();
        return this;
      }

      private long gasAllowancePerSettlement_ ;
      /**
       * <code>uint64 gas_allowance_per_settlement = 8 [(.gogoproto.jsontag) = "gas_allowance_per_settlement", (.gogoproto.moretags) = "yaml:&#92;"gas_allowance_per_settlement&#92;""];</code>
       * @return The gasAllowancePerSettlement.
       */
      @java.lang.Override
      public long getGasAllowancePerSettlement() {
        return gasAllowancePerSettlement_;
      }
      /**
       * <code>uint64 gas_allowance_per_settlement = 8 [(.gogoproto.jsontag) = "gas_allowance_per_settlement", (.gogoproto.moretags) = "yaml:&#92;"gas_allowance_per_settlement&#92;""];</code>
       * @param value The gasAllowancePerSettlement to set.
       * @return This builder for chaining.
       */
      public Builder setGasAllowancePerSettlement(long value) {

        gasAllowancePerSettlement_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 gas_allowance_per_settlement = 8 [(.gogoproto.jsontag) = "gas_allowance_per_settlement", (.gogoproto.moretags) = "yaml:&#92;"gas_allowance_per_settlement&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearGasAllowancePerSettlement() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gasAllowancePerSettlement_ = 0L;
        onChanged();
        return this;
      }

      private long minProcessableRent_ ;
      /**
       * <code>uint64 min_processable_rent = 9 [(.gogoproto.jsontag) = "min_processable_rent", (.gogoproto.moretags) = "yaml:&#92;"min_processable_rent&#92;""];</code>
       * @return The minProcessableRent.
       */
      @java.lang.Override
      public long getMinProcessableRent() {
        return minProcessableRent_;
      }
      /**
       * <code>uint64 min_processable_rent = 9 [(.gogoproto.jsontag) = "min_processable_rent", (.gogoproto.moretags) = "yaml:&#92;"min_processable_rent&#92;""];</code>
       * @param value The minProcessableRent to set.
       * @return This builder for chaining.
       */
      public Builder setMinProcessableRent(long value) {

        minProcessableRent_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 min_processable_rent = 9 [(.gogoproto.jsontag) = "min_processable_rent", (.gogoproto.moretags) = "yaml:&#92;"min_processable_rent&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinProcessableRent() {
        bitField0_ = (bitField0_ & ~0x00000100);
        minProcessableRent_ = 0L;
        onChanged();
        return this;
      }

      private long orderBookEntriesPerLoad_ ;
      /**
       * <code>uint64 order_book_entries_per_load = 10 [(.gogoproto.jsontag) = "order_book_entries_per_load", (.gogoproto.moretags) = "yaml:&#92;"order_book_entries_per_load&#92;""];</code>
       * @return The orderBookEntriesPerLoad.
       */
      @java.lang.Override
      public long getOrderBookEntriesPerLoad() {
        return orderBookEntriesPerLoad_;
      }
      /**
       * <code>uint64 order_book_entries_per_load = 10 [(.gogoproto.jsontag) = "order_book_entries_per_load", (.gogoproto.moretags) = "yaml:&#92;"order_book_entries_per_load&#92;""];</code>
       * @param value The orderBookEntriesPerLoad to set.
       * @return This builder for chaining.
       */
      public Builder setOrderBookEntriesPerLoad(long value) {

        orderBookEntriesPerLoad_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 order_book_entries_per_load = 10 [(.gogoproto.jsontag) = "order_book_entries_per_load", (.gogoproto.moretags) = "yaml:&#92;"order_book_entries_per_load&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderBookEntriesPerLoad() {
        bitField0_ = (bitField0_ & ~0x00000200);
        orderBookEntriesPerLoad_ = 0L;
        onChanged();
        return this;
      }

      private long contractUnsuspendCost_ ;
      /**
       * <code>uint64 contract_unsuspend_cost = 11 [(.gogoproto.jsontag) = "contract_unsuspend_cost", (.gogoproto.moretags) = "yaml:&#92;"contract_unsuspend_cost&#92;""];</code>
       * @return The contractUnsuspendCost.
       */
      @java.lang.Override
      public long getContractUnsuspendCost() {
        return contractUnsuspendCost_;
      }
      /**
       * <code>uint64 contract_unsuspend_cost = 11 [(.gogoproto.jsontag) = "contract_unsuspend_cost", (.gogoproto.moretags) = "yaml:&#92;"contract_unsuspend_cost&#92;""];</code>
       * @param value The contractUnsuspendCost to set.
       * @return This builder for chaining.
       */
      public Builder setContractUnsuspendCost(long value) {

        contractUnsuspendCost_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 contract_unsuspend_cost = 11 [(.gogoproto.jsontag) = "contract_unsuspend_cost", (.gogoproto.moretags) = "yaml:&#92;"contract_unsuspend_cost&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearContractUnsuspendCost() {
        bitField0_ = (bitField0_ & ~0x00000400);
        contractUnsuspendCost_ = 0L;
        onChanged();
        return this;
      }

      private long maxOrderPerPrice_ ;
      /**
       * <code>uint64 max_order_per_price = 12 [(.gogoproto.jsontag) = "max_order_per_price", (.gogoproto.moretags) = "yaml:&#92;"max_order_per_price&#92;""];</code>
       * @return The maxOrderPerPrice.
       */
      @java.lang.Override
      public long getMaxOrderPerPrice() {
        return maxOrderPerPrice_;
      }
      /**
       * <code>uint64 max_order_per_price = 12 [(.gogoproto.jsontag) = "max_order_per_price", (.gogoproto.moretags) = "yaml:&#92;"max_order_per_price&#92;""];</code>
       * @param value The maxOrderPerPrice to set.
       * @return This builder for chaining.
       */
      public Builder setMaxOrderPerPrice(long value) {

        maxOrderPerPrice_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 max_order_per_price = 12 [(.gogoproto.jsontag) = "max_order_per_price", (.gogoproto.moretags) = "yaml:&#92;"max_order_per_price&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxOrderPerPrice() {
        bitField0_ = (bitField0_ & ~0x00000800);
        maxOrderPerPrice_ = 0L;
        onChanged();
        return this;
      }

      private long maxPairsPerContract_ ;
      /**
       * <code>uint64 max_pairs_per_contract = 13 [(.gogoproto.jsontag) = "max_pairs_per_contract", (.gogoproto.moretags) = "yaml:&#92;"max_pairs_per_contract&#92;""];</code>
       * @return The maxPairsPerContract.
       */
      @java.lang.Override
      public long getMaxPairsPerContract() {
        return maxPairsPerContract_;
      }
      /**
       * <code>uint64 max_pairs_per_contract = 13 [(.gogoproto.jsontag) = "max_pairs_per_contract", (.gogoproto.moretags) = "yaml:&#92;"max_pairs_per_contract&#92;""];</code>
       * @param value The maxPairsPerContract to set.
       * @return This builder for chaining.
       */
      public Builder setMaxPairsPerContract(long value) {

        maxPairsPerContract_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 max_pairs_per_contract = 13 [(.gogoproto.jsontag) = "max_pairs_per_contract", (.gogoproto.moretags) = "yaml:&#92;"max_pairs_per_contract&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxPairsPerContract() {
        bitField0_ = (bitField0_ & ~0x00001000);
        maxPairsPerContract_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:seiprotocol.seichain.dex.Params)
    }

    // @@protoc_insertion_point(class_scope:seiprotocol.seichain.dex.Params)
    private static final seiprotocol.seichain.dex.ParamsOuterClass.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new seiprotocol.seichain.dex.ParamsOuterClass.Params();
    }

    public static seiprotocol.seichain.dex.ParamsOuterClass.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      @java.lang.Override
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public seiprotocol.seichain.dex.ParamsOuterClass.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seiprotocol_seichain_dex_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seiprotocol_seichain_dex_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dex/params.proto\022\030seiprotocol.seichain" +
      ".dex\032\024gogoproto/gogo.proto\"\314\t\n\006Params\022a\n" +
      "\030price_snapshot_retention\030\001 \001(\004B?\352\336\037\030pri" +
      "ce_snapshot_retention\362\336\037\037yaml:\"price_sna" +
      "pshot_retention\"\022b\n\023sudo_call_gas_price\030" +
      "\002 \001(\tBE\310\336\037\000\332\336\037&github.com/cosmos/cosmos-" +
      "sdk/types.Dec\352\336\037\023sudo_call_gas_price\022X\n\025" +
      "begin_block_gas_limit\030\003 \001(\004B9\352\336\037\025begin_b" +
      "lock_gas_limit\362\336\037\034yaml:\"begin_block_gas_" +
      "limit\"\022R\n\023end_block_gas_limit\030\004 \001(\004B5\352\336\037" +
      "\023end_block_gas_limit\362\336\037\032yaml:\"end_block_" +
      "gas_limit\"\022X\n\025default_gas_per_order\030\005 \001(" +
      "\004B9\352\336\037\025default_gas_per_order\362\336\037\034yaml:\"de" +
      "fault_gas_per_order\"\022[\n\026default_gas_per_" +
      "cancel\030\006 \001(\004B;\352\336\037\026default_gas_per_cancel" +
      "\362\336\037\035yaml:\"default_gas_per_cancel\"\022I\n\020min" +
      "_rent_deposit\030\007 \001(\004B/\352\336\037\020min_rent_deposi" +
      "t\362\336\037\027yaml:\"min_rent_deposit\"\022m\n\034gas_allo" +
      "wance_per_settlement\030\010 \001(\004BG\352\336\037\034gas_allo" +
      "wance_per_settlement\362\336\037#yaml:\"gas_allowa" +
      "nce_per_settlement\"\022U\n\024min_processable_r" +
      "ent\030\t \001(\004B7\352\336\037\024min_processable_rent\362\336\037\033y" +
      "aml:\"min_processable_rent\"\022j\n\033order_book" +
      "_entries_per_load\030\n \001(\004BE\352\336\037\033order_book_" +
      "entries_per_load\362\336\037\"yaml:\"order_book_ent" +
      "ries_per_load\"\022^\n\027contract_unsuspend_cos" +
      "t\030\013 \001(\004B=\352\336\037\027contract_unsuspend_cost\362\336\037\036" +
      "yaml:\"contract_unsuspend_cost\"\022R\n\023max_or" +
      "der_per_price\030\014 \001(\004B5\352\336\037\023max_order_per_p" +
      "rice\362\336\037\032yaml:\"max_order_per_price\"\022[\n\026ma" +
      "x_pairs_per_contract\030\r \001(\004B;\352\336\037\026max_pair" +
      "s_per_contract\362\336\037\035yaml:\"max_pairs_per_co" +
      "ntract\":\010\230\240\037\000\350\240\037\001B/Z-github.com/sei-prot" +
      "ocol/sei-chain/x/dex/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_seiprotocol_seichain_dex_Params_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_seiprotocol_seichain_dex_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seiprotocol_seichain_dex_Params_descriptor,
        new java.lang.String[] { "PriceSnapshotRetention", "SudoCallGasPrice", "BeginBlockGasLimit", "EndBlockGasLimit", "DefaultGasPerOrder", "DefaultGasPerCancel", "MinRentDeposit", "GasAllowancePerSettlement", "MinProcessableRent", "OrderBookEntriesPerLoad", "ContractUnsuspendCost", "MaxOrderPerPrice", "MaxPairsPerContract", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customtype);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.jsontag);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
