// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oracle/tx.proto

package seiprotocol.seichain.oracle;

public final class Tx {
  private Tx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAggregateExchangeRateVoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 1 reserved from old field `salt`
     * </pre>
     *
     * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
     * @return The exchangeRates.
     */
    java.lang.String getExchangeRates();
    /**
     * <pre>
     * 1 reserved from old field `salt`
     * </pre>
     *
     * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
     * @return The bytes for exchangeRates.
     */
    com.google.protobuf.ByteString
        getExchangeRatesBytes();

    /**
     * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
     * @return The feeder.
     */
    java.lang.String getFeeder();
    /**
     * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
     * @return The bytes for feeder.
     */
    com.google.protobuf.ByteString
        getFeederBytes();

    /**
     * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
     * @return The validator.
     */
    java.lang.String getValidator();
    /**
     * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
     * @return The bytes for validator.
     */
    com.google.protobuf.ByteString
        getValidatorBytes();
  }
  /**
   * <pre>
   * MsgAggregateExchangeRateVote represents a message to submit
   * aggregate exchange rate vote.
   * </pre>
   *
   * Protobuf type {@code seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote}
   */
  public static final class MsgAggregateExchangeRateVote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote)
      MsgAggregateExchangeRateVoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAggregateExchangeRateVote.newBuilder() to construct.
    private MsgAggregateExchangeRateVote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAggregateExchangeRateVote() {
      exchangeRates_ = "";
      feeder_ = "";
      validator_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgAggregateExchangeRateVote();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.class, seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.Builder.class);
    }

    public static final int EXCHANGE_RATES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object exchangeRates_ = "";
    /**
     * <pre>
     * 1 reserved from old field `salt`
     * </pre>
     *
     * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
     * @return The exchangeRates.
     */
    @java.lang.Override
    public java.lang.String getExchangeRates() {
      java.lang.Object ref = exchangeRates_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeRates_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 1 reserved from old field `salt`
     * </pre>
     *
     * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
     * @return The bytes for exchangeRates.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExchangeRatesBytes() {
      java.lang.Object ref = exchangeRates_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeRates_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEEDER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object feeder_ = "";
    /**
     * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
     * @return The feeder.
     */
    @java.lang.Override
    public java.lang.String getFeeder() {
      java.lang.Object ref = feeder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feeder_ = s;
        return s;
      }
    }
    /**
     * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
     * @return The bytes for feeder.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFeederBytes() {
      java.lang.Object ref = feeder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feeder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDATOR_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object validator_ = "";
    /**
     * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
     * @return The validator.
     */
    @java.lang.Override
    public java.lang.String getValidator() {
      java.lang.Object ref = validator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validator_ = s;
        return s;
      }
    }
    /**
     * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
     * @return The bytes for validator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValidatorBytes() {
      java.lang.Object ref = validator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exchangeRates_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exchangeRates_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feeder_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, feeder_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validator_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, validator_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exchangeRates_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exchangeRates_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feeder_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, feeder_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validator_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, validator_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote)) {
        return super.equals(obj);
      }
      seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote other = (seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote) obj;

      if (!getExchangeRates()
          .equals(other.getExchangeRates())) return false;
      if (!getFeeder()
          .equals(other.getFeeder())) return false;
      if (!getValidator()
          .equals(other.getValidator())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXCHANGE_RATES_FIELD_NUMBER;
      hash = (53 * hash) + getExchangeRates().hashCode();
      hash = (37 * hash) + FEEDER_FIELD_NUMBER;
      hash = (53 * hash) + getFeeder().hashCode();
      hash = (37 * hash) + VALIDATOR_FIELD_NUMBER;
      hash = (53 * hash) + getValidator().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgAggregateExchangeRateVote represents a message to submit
     * aggregate exchange rate vote.
     * </pre>
     *
     * Protobuf type {@code seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote)
        seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.class, seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.Builder.class);
      }

      // Construct using seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        exchangeRates_ = "";
        feeder_ = "";
        validator_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_descriptor;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote getDefaultInstanceForType() {
        return seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.getDefaultInstance();
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote build() {
        seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote buildPartial() {
        seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote result = new seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.exchangeRates_ = exchangeRates_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.feeder_ = feeder_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.validator_ = validator_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote) {
          return mergeFrom((seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote other) {
        if (other == seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote.getDefaultInstance()) return this;
        if (!other.getExchangeRates().isEmpty()) {
          exchangeRates_ = other.exchangeRates_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFeeder().isEmpty()) {
          feeder_ = other.feeder_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getValidator().isEmpty()) {
          validator_ = other.validator_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                exchangeRates_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 26: {
                feeder_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 34: {
                validator_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object exchangeRates_ = "";
      /**
       * <pre>
       * 1 reserved from old field `salt`
       * </pre>
       *
       * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
       * @return The exchangeRates.
       */
      public java.lang.String getExchangeRates() {
        java.lang.Object ref = exchangeRates_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchangeRates_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 1 reserved from old field `salt`
       * </pre>
       *
       * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
       * @return The bytes for exchangeRates.
       */
      public com.google.protobuf.ByteString
          getExchangeRatesBytes() {
        java.lang.Object ref = exchangeRates_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchangeRates_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 1 reserved from old field `salt`
       * </pre>
       *
       * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
       * @param value The exchangeRates to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeRates(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        exchangeRates_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1 reserved from old field `salt`
       * </pre>
       *
       * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearExchangeRates() {
        exchangeRates_ = getDefaultInstance().getExchangeRates();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1 reserved from old field `salt`
       * </pre>
       *
       * <code>string exchange_rates = 2 [(.gogoproto.moretags) = "yaml:&#92;"exchange_rates&#92;""];</code>
       * @param value The bytes for exchangeRates to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeRatesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        exchangeRates_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object feeder_ = "";
      /**
       * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
       * @return The feeder.
       */
      public java.lang.String getFeeder() {
        java.lang.Object ref = feeder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          feeder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
       * @return The bytes for feeder.
       */
      public com.google.protobuf.ByteString
          getFeederBytes() {
        java.lang.Object ref = feeder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          feeder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
       * @param value The feeder to set.
       * @return This builder for chaining.
       */
      public Builder setFeeder(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        feeder_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeder() {
        feeder_ = getDefaultInstance().getFeeder();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string feeder = 3 [(.gogoproto.moretags) = "yaml:&#92;"feeder&#92;""];</code>
       * @param value The bytes for feeder to set.
       * @return This builder for chaining.
       */
      public Builder setFeederBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        feeder_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object validator_ = "";
      /**
       * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
       * @return The validator.
       */
      public java.lang.String getValidator() {
        java.lang.Object ref = validator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          validator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
       * @return The bytes for validator.
       */
      public com.google.protobuf.ByteString
          getValidatorBytes() {
        java.lang.Object ref = validator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          validator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
       * @param value The validator to set.
       * @return This builder for chaining.
       */
      public Builder setValidator(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        validator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearValidator() {
        validator_ = getDefaultInstance().getValidator();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string validator = 4 [(.gogoproto.moretags) = "yaml:&#92;"validator&#92;""];</code>
       * @param value The bytes for validator to set.
       * @return This builder for chaining.
       */
      public Builder setValidatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        validator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote)
    }

    // @@protoc_insertion_point(class_scope:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVote)
    private static final seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote();
    }

    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAggregateExchangeRateVote>
        PARSER = new com.google.protobuf.AbstractParser<MsgAggregateExchangeRateVote>() {
      @java.lang.Override
      public MsgAggregateExchangeRateVote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgAggregateExchangeRateVote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAggregateExchangeRateVote> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgAggregateExchangeRateVoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * MsgAggregateExchangeRateVoteResponse defines the Msg/AggregateExchangeRateVote response type.
   * </pre>
   *
   * Protobuf type {@code seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse}
   */
  public static final class MsgAggregateExchangeRateVoteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse)
      MsgAggregateExchangeRateVoteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAggregateExchangeRateVoteResponse.newBuilder() to construct.
    private MsgAggregateExchangeRateVoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAggregateExchangeRateVoteResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgAggregateExchangeRateVoteResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.class, seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse)) {
        return super.equals(obj);
      }
      seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse other = (seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgAggregateExchangeRateVoteResponse defines the Msg/AggregateExchangeRateVote response type.
     * </pre>
     *
     * Protobuf type {@code seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse)
        seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.class, seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.Builder.class);
      }

      // Construct using seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_descriptor;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse getDefaultInstanceForType() {
        return seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.getDefaultInstance();
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse build() {
        seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse buildPartial() {
        seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse result = new seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse) {
          return mergeFrom((seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse other) {
        if (other == seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse)
    }

    // @@protoc_insertion_point(class_scope:seiprotocol.seichain.oracle.MsgAggregateExchangeRateVoteResponse)
    private static final seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse();
    }

    public static seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAggregateExchangeRateVoteResponse>
        PARSER = new com.google.protobuf.AbstractParser<MsgAggregateExchangeRateVoteResponse>() {
      @java.lang.Override
      public MsgAggregateExchangeRateVoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgAggregateExchangeRateVoteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAggregateExchangeRateVoteResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public seiprotocol.seichain.oracle.Tx.MsgAggregateExchangeRateVoteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgDelegateFeedConsentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seiprotocol.seichain.oracle.MsgDelegateFeedConsent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
     * @return The operator.
     */
    java.lang.String getOperator();
    /**
     * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
     * @return The bytes for operator.
     */
    com.google.protobuf.ByteString
        getOperatorBytes();

    /**
     * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
     * @return The delegate.
     */
    java.lang.String getDelegate();
    /**
     * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
     * @return The bytes for delegate.
     */
    com.google.protobuf.ByteString
        getDelegateBytes();
  }
  /**
   * <pre>
   * MsgDelegateFeedConsent represents a message to
   * delegate oracle voting rights to another address.
   * </pre>
   *
   * Protobuf type {@code seiprotocol.seichain.oracle.MsgDelegateFeedConsent}
   */
  public static final class MsgDelegateFeedConsent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seiprotocol.seichain.oracle.MsgDelegateFeedConsent)
      MsgDelegateFeedConsentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgDelegateFeedConsent.newBuilder() to construct.
    private MsgDelegateFeedConsent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgDelegateFeedConsent() {
      operator_ = "";
      delegate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgDelegateFeedConsent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.class, seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.Builder.class);
    }

    public static final int OPERATOR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object operator_ = "";
    /**
     * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
     * @return The operator.
     */
    @java.lang.Override
    public java.lang.String getOperator() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operator_ = s;
        return s;
      }
    }
    /**
     * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
     * @return The bytes for operator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELEGATE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object delegate_ = "";
    /**
     * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
     * @return The delegate.
     */
    @java.lang.Override
    public java.lang.String getDelegate() {
      java.lang.Object ref = delegate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        delegate_ = s;
        return s;
      }
    }
    /**
     * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
     * @return The bytes for delegate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDelegateBytes() {
      java.lang.Object ref = delegate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delegate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operator_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(delegate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, delegate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operator_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(delegate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, delegate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent)) {
        return super.equals(obj);
      }
      seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent other = (seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent) obj;

      if (!getOperator()
          .equals(other.getOperator())) return false;
      if (!getDelegate()
          .equals(other.getDelegate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
      hash = (53 * hash) + getOperator().hashCode();
      hash = (37 * hash) + DELEGATE_FIELD_NUMBER;
      hash = (53 * hash) + getDelegate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgDelegateFeedConsent represents a message to
     * delegate oracle voting rights to another address.
     * </pre>
     *
     * Protobuf type {@code seiprotocol.seichain.oracle.MsgDelegateFeedConsent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seiprotocol.seichain.oracle.MsgDelegateFeedConsent)
        seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.class, seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.Builder.class);
      }

      // Construct using seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        operator_ = "";
        delegate_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_descriptor;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent getDefaultInstanceForType() {
        return seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.getDefaultInstance();
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent build() {
        seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent buildPartial() {
        seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent result = new seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.operator_ = operator_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.delegate_ = delegate_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent) {
          return mergeFrom((seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent other) {
        if (other == seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent.getDefaultInstance()) return this;
        if (!other.getOperator().isEmpty()) {
          operator_ = other.operator_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDelegate().isEmpty()) {
          delegate_ = other.delegate_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                operator_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                delegate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object operator_ = "";
      /**
       * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
       * @return The operator.
       */
      public java.lang.String getOperator() {
        java.lang.Object ref = operator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
       * @return The bytes for operator.
       */
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        java.lang.Object ref = operator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
       * @param value The operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperator(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        operator_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearOperator() {
        operator_ = getDefaultInstance().getOperator();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 1 [(.gogoproto.moretags) = "yaml:&#92;"operator&#92;""];</code>
       * @param value The bytes for operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        operator_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object delegate_ = "";
      /**
       * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
       * @return The delegate.
       */
      public java.lang.String getDelegate() {
        java.lang.Object ref = delegate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          delegate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
       * @return The bytes for delegate.
       */
      public com.google.protobuf.ByteString
          getDelegateBytes() {
        java.lang.Object ref = delegate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          delegate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
       * @param value The delegate to set.
       * @return This builder for chaining.
       */
      public Builder setDelegate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        delegate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearDelegate() {
        delegate_ = getDefaultInstance().getDelegate();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string delegate = 2 [(.gogoproto.moretags) = "yaml:&#92;"delegate&#92;""];</code>
       * @param value The bytes for delegate to set.
       * @return This builder for chaining.
       */
      public Builder setDelegateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        delegate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:seiprotocol.seichain.oracle.MsgDelegateFeedConsent)
    }

    // @@protoc_insertion_point(class_scope:seiprotocol.seichain.oracle.MsgDelegateFeedConsent)
    private static final seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent();
    }

    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgDelegateFeedConsent>
        PARSER = new com.google.protobuf.AbstractParser<MsgDelegateFeedConsent>() {
      @java.lang.Override
      public MsgDelegateFeedConsent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgDelegateFeedConsent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgDelegateFeedConsent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgDelegateFeedConsentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * MsgDelegateFeedConsentResponse defines the Msg/DelegateFeedConsent response type.
   * </pre>
   *
   * Protobuf type {@code seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse}
   */
  public static final class MsgDelegateFeedConsentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse)
      MsgDelegateFeedConsentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgDelegateFeedConsentResponse.newBuilder() to construct.
    private MsgDelegateFeedConsentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgDelegateFeedConsentResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgDelegateFeedConsentResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.class, seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse)) {
        return super.equals(obj);
      }
      seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse other = (seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgDelegateFeedConsentResponse defines the Msg/DelegateFeedConsent response type.
     * </pre>
     *
     * Protobuf type {@code seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse)
        seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.class, seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.Builder.class);
      }

      // Construct using seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return seiprotocol.seichain.oracle.Tx.internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_descriptor;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse getDefaultInstanceForType() {
        return seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse build() {
        seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse buildPartial() {
        seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse result = new seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse) {
          return mergeFrom((seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse other) {
        if (other == seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse)
    }

    // @@protoc_insertion_point(class_scope:seiprotocol.seichain.oracle.MsgDelegateFeedConsentResponse)
    private static final seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse();
    }

    public static seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgDelegateFeedConsentResponse>
        PARSER = new com.google.protobuf.AbstractParser<MsgDelegateFeedConsentResponse>() {
      @java.lang.Override
      public MsgDelegateFeedConsentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgDelegateFeedConsentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgDelegateFeedConsentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public seiprotocol.seichain.oracle.Tx.MsgDelegateFeedConsentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017oracle/tx.proto\022\033seiprotocol.seichain." +
      "oracle\032\024gogoproto/gogo.proto\"\247\001\n\034MsgAggr" +
      "egateExchangeRateVote\0221\n\016exchange_rates\030" +
      "\002 \001(\tB\031\362\336\037\025yaml:\"exchange_rates\"\022!\n\006feed" +
      "er\030\003 \001(\tB\021\362\336\037\ryaml:\"feeder\"\022\'\n\tvalidator" +
      "\030\004 \001(\tB\024\362\336\037\020yaml:\"validator\":\010\210\240\037\000\350\240\037\000\"&" +
      "\n$MsgAggregateExchangeRateVoteResponse\"p" +
      "\n\026MsgDelegateFeedConsent\022%\n\010operator\030\001 \001" +
      "(\tB\023\362\336\037\017yaml:\"operator\"\022%\n\010delegate\030\002 \001(" +
      "\tB\023\362\336\037\017yaml:\"delegate\":\010\210\240\037\000\350\240\037\000\" \n\036MsgD" +
      "elegateFeedConsentResponse2\253\002\n\003Msg\022\231\001\n\031A" +
      "ggregateExchangeRateVote\0229.seiprotocol.s" +
      "eichain.oracle.MsgAggregateExchangeRateV" +
      "ote\032A.seiprotocol.seichain.oracle.MsgAgg" +
      "regateExchangeRateVoteResponse\022\207\001\n\023Deleg" +
      "ateFeedConsent\0223.seiprotocol.seichain.or" +
      "acle.MsgDelegateFeedConsent\032;.seiprotoco" +
      "l.seichain.oracle.MsgDelegateFeedConsent" +
      "ResponseB2Z0github.com/sei-protocol/sei-" +
      "chain/x/oracle/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVote_descriptor,
        new java.lang.String[] { "ExchangeRates", "Feeder", "Validator", });
    internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seiprotocol_seichain_oracle_MsgAggregateExchangeRateVoteResponse_descriptor,
        new java.lang.String[] { });
    internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsent_descriptor,
        new java.lang.String[] { "Operator", "Delegate", });
    internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seiprotocol_seichain_oracle_MsgDelegateFeedConsentResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
