// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alliance/unbonding.proto

package alliance;

public final class Unbonding {
  private Unbonding() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnbondingDelegationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:alliance.UnbondingDelegation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * completion_time is the unix time for unbonding completion.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the completionTime field is set.
     */
    boolean hasCompletionTime();
    /**
     * <pre>
     * completion_time is the unix time for unbonding completion.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The completionTime.
     */
    com.google.protobuf.Timestamp getCompletionTime();
    /**
     * <pre>
     * completion_time is the unix time for unbonding completion.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    com.google.protobuf.TimestampOrBuilder getCompletionTimeOrBuilder();

    /**
     * <pre>
     * validator_address is the bech32-encoded address of the validator.
     * </pre>
     *
     * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The validatorAddress.
     */
    java.lang.String getValidatorAddress();
    /**
     * <pre>
     * validator_address is the bech32-encoded address of the validator.
     * </pre>
     *
     * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The bytes for validatorAddress.
     */
    com.google.protobuf.ByteString
        getValidatorAddressBytes();

    /**
     * <pre>
     * amount defines the tokens to receive at completion.
     * </pre>
     *
     * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
     * @return The amount.
     */
    java.lang.String getAmount();
    /**
     * <pre>
     * amount defines the tokens to receive at completion.
     * </pre>
     *
     * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
     * @return The bytes for amount.
     */
    com.google.protobuf.ByteString
        getAmountBytes();
  }
  /**
   * <pre>
   * UnbondingDelegation defines an unbonding object with relevant metadata.
   * </pre>
   *
   * Protobuf type {@code alliance.UnbondingDelegation}
   */
  public static final class UnbondingDelegation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:alliance.UnbondingDelegation)
      UnbondingDelegationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnbondingDelegation.newBuilder() to construct.
    private UnbondingDelegation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnbondingDelegation() {
      validatorAddress_ = "";
      amount_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UnbondingDelegation();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alliance.Unbonding.internal_static_alliance_UnbondingDelegation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alliance.Unbonding.internal_static_alliance_UnbondingDelegation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alliance.Unbonding.UnbondingDelegation.class, alliance.Unbonding.UnbondingDelegation.Builder.class);
    }

    public static final int COMPLETION_TIME_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp completionTime_;
    /**
     * <pre>
     * completion_time is the unix time for unbonding completion.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the completionTime field is set.
     */
    @java.lang.Override
    public boolean hasCompletionTime() {
      return completionTime_ != null;
    }
    /**
     * <pre>
     * completion_time is the unix time for unbonding completion.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The completionTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCompletionTime() {
      return completionTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completionTime_;
    }
    /**
     * <pre>
     * completion_time is the unix time for unbonding completion.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCompletionTimeOrBuilder() {
      return completionTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completionTime_;
    }

    public static final int VALIDATOR_ADDRESS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object validatorAddress_ = "";
    /**
     * <pre>
     * validator_address is the bech32-encoded address of the validator.
     * </pre>
     *
     * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The validatorAddress.
     */
    @java.lang.Override
    public java.lang.String getValidatorAddress() {
      java.lang.Object ref = validatorAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validatorAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * validator_address is the bech32-encoded address of the validator.
     * </pre>
     *
     * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The bytes for validatorAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValidatorAddressBytes() {
      java.lang.Object ref = validatorAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validatorAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object amount_ = "";
    /**
     * <pre>
     * amount defines the tokens to receive at completion.
     * </pre>
     *
     * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
     * @return The amount.
     */
    @java.lang.Override
    public java.lang.String getAmount() {
      java.lang.Object ref = amount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * amount defines the tokens to receive at completion.
     * </pre>
     *
     * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
     * @return The bytes for amount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAmountBytes() {
      java.lang.Object ref = amount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (completionTime_ != null) {
        output.writeMessage(1, getCompletionTime());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validatorAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, validatorAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, amount_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (completionTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCompletionTime());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validatorAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, validatorAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, amount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof alliance.Unbonding.UnbondingDelegation)) {
        return super.equals(obj);
      }
      alliance.Unbonding.UnbondingDelegation other = (alliance.Unbonding.UnbondingDelegation) obj;

      if (hasCompletionTime() != other.hasCompletionTime()) return false;
      if (hasCompletionTime()) {
        if (!getCompletionTime()
            .equals(other.getCompletionTime())) return false;
      }
      if (!getValidatorAddress()
          .equals(other.getValidatorAddress())) return false;
      if (!getAmount()
          .equals(other.getAmount())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCompletionTime()) {
        hash = (37 * hash) + COMPLETION_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getCompletionTime().hashCode();
      }
      hash = (37 * hash) + VALIDATOR_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getValidatorAddress().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static alliance.Unbonding.UnbondingDelegation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static alliance.Unbonding.UnbondingDelegation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static alliance.Unbonding.UnbondingDelegation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(alliance.Unbonding.UnbondingDelegation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * UnbondingDelegation defines an unbonding object with relevant metadata.
     * </pre>
     *
     * Protobuf type {@code alliance.UnbondingDelegation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:alliance.UnbondingDelegation)
        alliance.Unbonding.UnbondingDelegationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alliance.Unbonding.internal_static_alliance_UnbondingDelegation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alliance.Unbonding.internal_static_alliance_UnbondingDelegation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                alliance.Unbonding.UnbondingDelegation.class, alliance.Unbonding.UnbondingDelegation.Builder.class);
      }

      // Construct using alliance.Unbonding.UnbondingDelegation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        completionTime_ = null;
        if (completionTimeBuilder_ != null) {
          completionTimeBuilder_.dispose();
          completionTimeBuilder_ = null;
        }
        validatorAddress_ = "";
        amount_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alliance.Unbonding.internal_static_alliance_UnbondingDelegation_descriptor;
      }

      @java.lang.Override
      public alliance.Unbonding.UnbondingDelegation getDefaultInstanceForType() {
        return alliance.Unbonding.UnbondingDelegation.getDefaultInstance();
      }

      @java.lang.Override
      public alliance.Unbonding.UnbondingDelegation build() {
        alliance.Unbonding.UnbondingDelegation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public alliance.Unbonding.UnbondingDelegation buildPartial() {
        alliance.Unbonding.UnbondingDelegation result = new alliance.Unbonding.UnbondingDelegation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(alliance.Unbonding.UnbondingDelegation result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.completionTime_ = completionTimeBuilder_ == null
              ? completionTime_
              : completionTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.validatorAddress_ = validatorAddress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.amount_ = amount_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof alliance.Unbonding.UnbondingDelegation) {
          return mergeFrom((alliance.Unbonding.UnbondingDelegation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(alliance.Unbonding.UnbondingDelegation other) {
        if (other == alliance.Unbonding.UnbondingDelegation.getDefaultInstance()) return this;
        if (other.hasCompletionTime()) {
          mergeCompletionTime(other.getCompletionTime());
        }
        if (!other.getValidatorAddress().isEmpty()) {
          validatorAddress_ = other.validatorAddress_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAmount().isEmpty()) {
          amount_ = other.amount_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getCompletionTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                validatorAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                amount_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp completionTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> completionTimeBuilder_;
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       * @return Whether the completionTime field is set.
       */
      public boolean hasCompletionTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       * @return The completionTime.
       */
      public com.google.protobuf.Timestamp getCompletionTime() {
        if (completionTimeBuilder_ == null) {
          return completionTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : completionTime_;
        } else {
          return completionTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder setCompletionTime(com.google.protobuf.Timestamp value) {
        if (completionTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          completionTime_ = value;
        } else {
          completionTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder setCompletionTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (completionTimeBuilder_ == null) {
          completionTime_ = builderForValue.build();
        } else {
          completionTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder mergeCompletionTime(com.google.protobuf.Timestamp value) {
        if (completionTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            completionTime_ != null &&
            completionTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCompletionTimeBuilder().mergeFrom(value);
          } else {
            completionTime_ = value;
          }
        } else {
          completionTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder clearCompletionTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        completionTime_ = null;
        if (completionTimeBuilder_ != null) {
          completionTimeBuilder_.dispose();
          completionTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.Timestamp.Builder getCompletionTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCompletionTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCompletionTimeOrBuilder() {
        if (completionTimeBuilder_ != null) {
          return completionTimeBuilder_.getMessageOrBuilder();
        } else {
          return completionTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : completionTime_;
        }
      }
      /**
       * <pre>
       * completion_time is the unix time for unbonding completion.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp completion_time = 1 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCompletionTimeFieldBuilder() {
        if (completionTimeBuilder_ == null) {
          completionTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCompletionTime(),
                  getParentForChildren(),
                  isClean());
          completionTime_ = null;
        }
        return completionTimeBuilder_;
      }

      private java.lang.Object validatorAddress_ = "";
      /**
       * <pre>
       * validator_address is the bech32-encoded address of the validator.
       * </pre>
       *
       * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @return The validatorAddress.
       */
      public java.lang.String getValidatorAddress() {
        java.lang.Object ref = validatorAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          validatorAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * validator_address is the bech32-encoded address of the validator.
       * </pre>
       *
       * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @return The bytes for validatorAddress.
       */
      public com.google.protobuf.ByteString
          getValidatorAddressBytes() {
        java.lang.Object ref = validatorAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          validatorAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * validator_address is the bech32-encoded address of the validator.
       * </pre>
       *
       * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @param value The validatorAddress to set.
       * @return This builder for chaining.
       */
      public Builder setValidatorAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        validatorAddress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * validator_address is the bech32-encoded address of the validator.
       * </pre>
       *
       * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValidatorAddress() {
        validatorAddress_ = getDefaultInstance().getValidatorAddress();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * validator_address is the bech32-encoded address of the validator.
       * </pre>
       *
       * <code>string validator_address = 2 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @param value The bytes for validatorAddress to set.
       * @return This builder for chaining.
       */
      public Builder setValidatorAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        validatorAddress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object amount_ = "";
      /**
       * <pre>
       * amount defines the tokens to receive at completion.
       * </pre>
       *
       * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
       * @return The amount.
       */
      public java.lang.String getAmount() {
        java.lang.Object ref = amount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          amount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * amount defines the tokens to receive at completion.
       * </pre>
       *
       * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
       * @return The bytes for amount.
       */
      public com.google.protobuf.ByteString
          getAmountBytes() {
        java.lang.Object ref = amount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          amount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * amount defines the tokens to receive at completion.
       * </pre>
       *
       * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        amount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * amount defines the tokens to receive at completion.
       * </pre>
       *
       * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        amount_ = getDefaultInstance().getAmount();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * amount defines the tokens to receive at completion.
       * </pre>
       *
       * <code>string amount = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.cosmos_proto.scalar) = "cosmos.Int"];</code>
       * @param value The bytes for amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        amount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:alliance.UnbondingDelegation)
    }

    // @@protoc_insertion_point(class_scope:alliance.UnbondingDelegation)
    private static final alliance.Unbonding.UnbondingDelegation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new alliance.Unbonding.UnbondingDelegation();
    }

    public static alliance.Unbonding.UnbondingDelegation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnbondingDelegation>
        PARSER = new com.google.protobuf.AbstractParser<UnbondingDelegation>() {
      @java.lang.Override
      public UnbondingDelegation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UnbondingDelegation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnbondingDelegation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public alliance.Unbonding.UnbondingDelegation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alliance_UnbondingDelegation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alliance_UnbondingDelegation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030alliance/unbonding.proto\022\010alliance\032\024go" +
      "goproto/gogo.proto\032\031cosmos_proto/cosmos." +
      "proto\032\036google/protobuf/duration.proto\032\037g" +
      "oogle/protobuf/timestamp.proto\"\335\001\n\023Unbon" +
      "dingDelegation\022=\n\017completion_time\030\001 \001(\0132" +
      "\032.google.protobuf.TimestampB\010\310\336\037\000\220\337\037\001\0223\n" +
      "\021validator_address\030\002 \001(\tB\030\322\264-\024cosmos.Add" +
      "ressString\022L\n\006amount\030\003 \001(\tB<\310\336\037\000\332\336\037&gith" +
      "ub.com/cosmos/cosmos-sdk/types.Int\322\264-\nco" +
      "smos.Int:\004\350\240\037\001B2Z0github.com/terra-money" +
      "/alliance/x/alliance/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          cosmos_proto.Cosmos.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_alliance_UnbondingDelegation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alliance_UnbondingDelegation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alliance_UnbondingDelegation_descriptor,
        new java.lang.String[] { "CompletionTime", "ValidatorAddress", "Amount", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(cosmos_proto.Cosmos.scalar);
    registry.add(com.google.protobuf.GoGoProtos.customtype);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    registry.add(com.google.protobuf.GoGoProtos.stdtime);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    cosmos_proto.Cosmos.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
